package com.spush.mapper;

import com.spush.pojo.DeveloperInfo;

public interface DeveloperInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String devId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer_info
     *
     * @mbggenerated
     */
    int insert(DeveloperInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer_info
     *
     * @mbggenerated
     */
    int insertSelective(DeveloperInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer_info
     *
     * @mbggenerated
     */
    DeveloperInfo selectByPrimaryKey(String devId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeveloperInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeveloperInfo record);
}