package com.spush.mapper;

import com.spush.pojo.DeviceInfo;

public interface DeviceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    int insert(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    int insertSelective(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    DeviceInfo selectByPrimaryKey(String deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeviceInfo record);
}