package com.spush.mapper;

import com.spush.pojo.UserToDevice;

public interface UserToDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_to_device
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_to_device
     *
     * @mbggenerated
     */
    int insert(UserToDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_to_device
     *
     * @mbggenerated
     */
    int insertSelective(UserToDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_to_device
     *
     * @mbggenerated
     */
    UserToDevice selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_to_device
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserToDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_to_device
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserToDevice record);
}