package com.spush.pojo;

import java.util.Date;

public class AppUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.app_id
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.user_type
     *
     * @mbggenerated
     */
    private Short userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.reg_time
     *
     * @mbggenerated
     */
    private Date regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.last_loadtime
     *
     * @mbggenerated
     */
    private Date lastLoadtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.user_id
     *
     * @return the value of app_user.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.user_id
     *
     * @param userId the value for app_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.app_id
     *
     * @return the value of app_user.app_id
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.app_id
     *
     * @param appId the value for app_user.app_id
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.user_type
     *
     * @return the value of app_user.user_type
     *
     * @mbggenerated
     */
    public Short getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.user_type
     *
     * @param userType the value for app_user.user_type
     *
     * @mbggenerated
     */
    public void setUserType(Short userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.reg_time
     *
     * @return the value of app_user.reg_time
     *
     * @mbggenerated
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.reg_time
     *
     * @param regTime the value for app_user.reg_time
     *
     * @mbggenerated
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.last_loadtime
     *
     * @return the value of app_user.last_loadtime
     *
     * @mbggenerated
     */
    public Date getLastLoadtime() {
        return lastLoadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.last_loadtime
     *
     * @param lastLoadtime the value for app_user.last_loadtime
     *
     * @mbggenerated
     */
    public void setLastLoadtime(Date lastLoadtime) {
        this.lastLoadtime = lastLoadtime;
    }
}