package com.spush.pojo;

import java.util.Date;

public class DeviceInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.device_id
     *
     * @mbggenerated
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.device_sid
     *
     * @mbggenerated
     */
    private String deviceSid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.device_name
     *
     * @mbggenerated
     */
    private String deviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.logo_url
     *
     * @mbggenerated
     */
    private String logoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.device_type
     *
     * @mbggenerated
     */
    private Short deviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.last_update
     *
     * @mbggenerated
     */
    private Date lastUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.device_id
     *
     * @return the value of device_info.device_id
     *
     * @mbggenerated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.device_id
     *
     * @param deviceId the value for device_info.device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.uid
     *
     * @return the value of device_info.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.uid
     *
     * @param uid the value for device_info.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.device_sid
     *
     * @return the value of device_info.device_sid
     *
     * @mbggenerated
     */
    public String getDeviceSid() {
        return deviceSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.device_sid
     *
     * @param deviceSid the value for device_info.device_sid
     *
     * @mbggenerated
     */
    public void setDeviceSid(String deviceSid) {
        this.deviceSid = deviceSid == null ? null : deviceSid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.device_name
     *
     * @return the value of device_info.device_name
     *
     * @mbggenerated
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.device_name
     *
     * @param deviceName the value for device_info.device_name
     *
     * @mbggenerated
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.logo_url
     *
     * @return the value of device_info.logo_url
     *
     * @mbggenerated
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.logo_url
     *
     * @param logoUrl the value for device_info.logo_url
     *
     * @mbggenerated
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl == null ? null : logoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.device_type
     *
     * @return the value of device_info.device_type
     *
     * @mbggenerated
     */
    public Short getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.device_type
     *
     * @param deviceType the value for device_info.device_type
     *
     * @mbggenerated
     */
    public void setDeviceType(Short deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.create_time
     *
     * @return the value of device_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.create_time
     *
     * @param createTime the value for device_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.last_update
     *
     * @return the value of device_info.last_update
     *
     * @mbggenerated
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.last_update
     *
     * @param lastUpdate the value for device_info.last_update
     *
     * @mbggenerated
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
}