package com.spush.pojo;

import java.util.Date;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.msg_id
     *
     * @mbggenerated
     */
    private String msgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.app_id
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.msg_type
     *
     * @mbggenerated
     */
    private Short msgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.push_type
     *
     * @mbggenerated
     */
    private Short pushType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.sendtime
     *
     * @mbggenerated
     */
    private Date sendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.send_num
     *
     * @mbggenerated
     */
    private Integer sendNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.rec_num
     *
     * @mbggenerated
     */
    private Integer recNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.open_num
     *
     * @mbggenerated
     */
    private Integer openNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.ingore_num
     *
     * @mbggenerated
     */
    private Integer ingoreNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.msg_id
     *
     * @return the value of message.msg_id
     *
     * @mbggenerated
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.msg_id
     *
     * @param msgId the value for message.msg_id
     *
     * @mbggenerated
     */
    public void setMsgId(String msgId) {
        this.msgId = msgId == null ? null : msgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.app_id
     *
     * @return the value of message.app_id
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.app_id
     *
     * @param appId the value for message.app_id
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.msg_type
     *
     * @return the value of message.msg_type
     *
     * @mbggenerated
     */
    public Short getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.msg_type
     *
     * @param msgType the value for message.msg_type
     *
     * @mbggenerated
     */
    public void setMsgType(Short msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.push_type
     *
     * @return the value of message.push_type
     *
     * @mbggenerated
     */
    public Short getPushType() {
        return pushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.push_type
     *
     * @param pushType the value for message.push_type
     *
     * @mbggenerated
     */
    public void setPushType(Short pushType) {
        this.pushType = pushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.sendtime
     *
     * @return the value of message.sendtime
     *
     * @mbggenerated
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.sendtime
     *
     * @param sendtime the value for message.sendtime
     *
     * @mbggenerated
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.send_num
     *
     * @return the value of message.send_num
     *
     * @mbggenerated
     */
    public Integer getSendNum() {
        return sendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.send_num
     *
     * @param sendNum the value for message.send_num
     *
     * @mbggenerated
     */
    public void setSendNum(Integer sendNum) {
        this.sendNum = sendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.rec_num
     *
     * @return the value of message.rec_num
     *
     * @mbggenerated
     */
    public Integer getRecNum() {
        return recNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.rec_num
     *
     * @param recNum the value for message.rec_num
     *
     * @mbggenerated
     */
    public void setRecNum(Integer recNum) {
        this.recNum = recNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.open_num
     *
     * @return the value of message.open_num
     *
     * @mbggenerated
     */
    public Integer getOpenNum() {
        return openNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.open_num
     *
     * @param openNum the value for message.open_num
     *
     * @mbggenerated
     */
    public void setOpenNum(Integer openNum) {
        this.openNum = openNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.ingore_num
     *
     * @return the value of message.ingore_num
     *
     * @mbggenerated
     */
    public Integer getIngoreNum() {
        return ingoreNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.ingore_num
     *
     * @param ingoreNum the value for message.ingore_num
     *
     * @mbggenerated
     */
    public void setIngoreNum(Integer ingoreNum) {
        this.ingoreNum = ingoreNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.status
     *
     * @return the value of message.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.status
     *
     * @param status the value for message.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}